services:
  strapi:
    build: .                   # usa build OPPURE image:, non entrambe
    # image: strapi/strapi:latest

    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapiDB
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PORT: 5432
      NODE_ENV: ${NODE_ENV}

      APP_KEYS_FILE: /run/secrets/app_keys
      API_TOKEN_SALT_FILE: /run/secrets/api_token_salt
      TRANSFER_TOKEN_SALT_FILE: /run/secrets/transfer_token_salt
      ADMIN_JWT_SECRET_FILE: /run/secrets/admin_jwt_secret
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      DATABASE_PASSWORD_FILE: /run/secrets/db_password

    secrets:
      - app_keys
      - api_token_salt
      - transfer_token_salt
      - admin_jwt_secret
      - jwt_secret
      - db_password

    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./data:/opt/app/data
      # - ./.env:/opt/app/.env    # meglio tenerlo disattivato in produzione
      - ./public/uploads:/opt/app/public/uploads
    # ports/networks/depends_on come già hai

  strapiDB:
    image: postgres:14.5-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
