services:
  strapi:
    build: . 
    # image: strapi/strapi:latest
    entrypoint: ["/opt/app/docker-entrypoint.sh"]
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapiDB
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PORT: 5432
      NODE_ENV: ${NODE_ENV}

      APP_KEYS_FILE: /run/secrets/app_keys
      API_TOKEN_SALT_FILE: /run/secrets/api_token_salt
      TRANSFER_TOKEN_SALT_FILE: /run/secrets/transfer_token_salt
      ADMIN_JWT_SECRET_FILE: /run/secrets/admin_jwt_secret
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      DATABASE_PASSWORD_FILE: /run/secrets/db_password

    secrets:
      - app_keys
      - api_token_salt
      - transfer_token_salt
      - admin_jwt_secret
      - jwt_secret
      - db_password

    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./data:/opt/app/data
      # - ./.env:/opt/app/.env    # meglio tenerlo disattivato in produzione
      - ./public/uploads:/opt/app/public/uploads
      - ../../docker/docker-entrypoint.sh:/opt/app/docker-entrypoint.sh:ro
    # ports/networks/depends_on come già hai

  strapiDB:
    image: postgres:14.5-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

      
  strapiAdminer:
    container_name: strapiAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=strapiDB
    networks:
      - strapi
    depends_on:
      - strapiDB

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
  reverse-proxy:
    external: true


secrets:
  app_keys:
    file: /opt/secure/strapi/app_keys.txt
  api_token_salt:
    file: /opt/secure/strapi/api_token_salt.txt
  admin_jwt_secret:
    file: /opt/secure/strapi/admin_jwt_secret.txt
  transfer_token_salt:
    file: /opt/secure/strapi/transfer_token_salt.txt
  jwt_secret:
    file: /opt/secure/strapi/jwt_secret.txt
  db_password:
    file: /opt/secure/strapi/db_password.txt