networks:
  reverse-proxy:
    external: true

services:
  fe:
    build:
      context: ../../services/fe   # percorso della cartella FE
      dockerfile: Dockerfile
      args:
        REACT_APP_STRAPI_API_URL: ${REACT_APP_STRAPI_API_URL:?}
        REACT_APP_SANTO_DEL_GIORNO_API_TOKEN: ${REACT_APP_SANTO_DEL_GIORNO_API_TOKEN:?}
        REACT_APP_STRAPI_TOKEN: ${REACT_APP_STRAPI_TOKEN:?}

    container_name: fe
    restart: unless-stopped
    networks:
      - reverse-proxy
    ports:
      - "3000:3000"
